### PR TITLE
Add kubernetes yaml file for remote training

### PR DESCRIPTION
**Pull request by EthanMarx**

### CODE REVIEW

**Comment by deepchatterjeeligo** [comment]
Ethan, can you also update the docs to show the usage.

**Comment by EthanMarx** [comment]
Yes will do - a couple other things I want to fix up as well.

**Comment by EthanMarx** [comment]
@deepchatterjeeligo added documentation and stream lined the process of setting one of these runs up. 

Did an end to end test using `amplfi-init` and everything worked smoothly

**Comment by EthanMarx** [comment]
@deepchatterjeeligo let me know how this looks. Looking to launch a run on nautilus.

**Comment by deepchatterjeeligo** [comment]
Sorry for not able to respond. But I would have suggested going ahead and merging this and then resolve any wrinkles.

**Pull request merged**
