### PR TITLE
Update `ml4gw` submodule commit

### PR DESCRIPTION
**Pull request by EthanMarx**
For some reason the `ml4gw` submodule was pointing to a stale commit. This points to the `v0.4.2` tag.

For now, this also removes the stale unit testing workflow.

### CODE REVIEW

**Comment by deepchatterjeeligo** [comment]
Do we need a submodule any longer? Specially if we use a tag

**Review by deepchatterjeeligo — CHANGES_REQUESTED** [review]
Let's either use the tag: https://github.com/ML4GW/amplfi/blob/main/projects/train/pyproject.toml#L11 . Or, since my sense is we will likely be using ml4gw `dev`, let's point to that branch instead.

**Comment by EthanMarx** [comment]
I think we should submodule, in case we need to iterate faster than `ml4gw` deployments

**Comment by EthanMarx** [comment]
@deepchatterjeeligo Alright we're pointing at dev

**Comment by deepchatterjeeligo** [comment]
sorry for the delay. thanks.

**Comment by deepchatterjeeligo** [comment]
This is not what I was asking, but fine for now.

**Review by deepchatterjeeligo — APPROVED** [review]

**Pull request merged**
